version: '2'

services:
  ddns:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/ddns/Dockerfile
    depends_on:
      - redis
    env_file: .env

  powerdns:
    restart: unless-stopped
    build:
      context: powerdns/
      dockerfile: Dockerfile
    depends_on:
      - ddns
    env_file: .env
    environment:
      PDNS_REMOTE_HTTP_HOST: "ddns:8053"

  redis:
    restart: unless-stopped
    image: redis:4-alpine